INSERT INTO T_USERS(USER_ID, USERNAME, PASSWORD, EMAIL) VALUES(1, 'Chandu', 'ChanduPASS', 'chandu@mail.com');
INSERT INTO T_USERS(USER_ID, USERNAME, PASSWORD, EMAIL) VALUES(2, 'Udaya', 'UdayaPASS', 'udaya@mail.com');
INSERT INTO T_USERS(USER_ID, USERNAME, PASSWORD, EMAIL) VALUES(3, 'Ramu', 'RamuPASS', 'ramu@mail.com');
INSERT INTO T_USERS(USER_ID, USERNAME, PASSWORD, EMAIL) VALUES(4, 'Ashok', 'AshokPASS', 'ashok@mail.com');
INSERT INTO T_USERS(USER_ID, USERNAME, PASSWORD, EMAIL) VALUES(5, 'Venkat', 'VenkatPASS', 'venkat@mail.com');